### PR TITLE
[ADD] af_sale_filters: AFC-1133 Added new module af_sale_filters to a…

### PR DESCRIPTION
**Pull request by rupareliyahemangi145**
…dd filter for client language and employee skills in sale.

### CODE REVIEW

**Comment by FredrikArvas** [comment]
Hi @iammiracle 
Could you please review this code  **af_sale_filters** and merge it to odoo-**sale**/Dev-12.0-Fenix-02-Branch.
Thanks

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
May I ask you to change/create a new PR to the Fenix-branch instead?
thanks

**Comment by rupareliyahemangi145** [comment]
Yes Sure @FredrikArvas I will create new PR.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've found two Fenix branch in odoo-af so I've create 2 PR.
Dev-12.0-Fenix-Sprint-02 - https://github.com/vertelab/odoo-af/pull/393
Dev-12.0-Fenix-branch - https://github.com/vertelab/odoo-af/pull/394

Closing this PR as created new PR.

**Comment by FredrikArvas** [comment]
Thanks
( The "Dev-12.0-Fenix-branch" is an old one that should not be used. )

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas

**Pull request closed without merging**
