### PR TITLE
[ADD] af_sale_orders: AFC-1278 Added new module af_sale_orders to cre…

### PR DESCRIPTION
**Pull request by rupareliyahemangi145**
…ated project and task based on selcted product.

### CODE REVIEW

**Comment by FredrikArvas** [comment]
This module should not be merged to odoo-af - it should be merged to odoo-sale.
Thanks

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas Should I create PR in odoo-sale?

**Comment by FredrikArvas** [comment]
yes please

**Comment by rupareliyahemangi145** [comment]
Ok Let me do it @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Created PR in odoo-sale https://github.com/vertelab/odoo-sale/pull/3.

**Pull request closed without merging**
