### PR TITLE
AFC-1313 Mail Client Odoo Messaging

### PR DESCRIPTION
**Pull request by iammiracle**

### CODE REVIEW

**Comment by iammiracle** [comment]
Two modules added: 

**af_mail_client_contact**
**af_mail_client_employee**

**Comment by arturchilangwa-vertel** [comment]
For issue: https://github.com/vertelab/odoo-af/issues/312 

Moved af_mail_client_contact to odoo-mail in this [PR](https://github.com/vertelab/odoo-mail/pull/1) 

Added this [commit](https://github.com/vertelab/odoo-af/pull/289/commits/b4754075bd3f41efb3374b7a5066948d8d3d269a) to remove af_mail_client from this PR

**Review by arturchilangwa-vertel — APPROVED** [review]
Looks good!

**Review by arturchilangwa-vertel — APPROVED** [review]

**Comment by FredrikArvas** [comment]
@arturchilangwa-vertel 
Could we merge this module?

**Pull request merged**
