### PR TITLE
[ADD] af_core_menu_disabling: Added Index file and Translation for af…

### PR DESCRIPTION
**Pull request by rupareliyahemangi145**
…_core_menu_disabling module and Removed dependency of website as no need.

### CODE REVIEW

**Review by timforsstromAF — APPROVED** [review]
Looks ok to me

**Comment by rupareliyahemangi145** [comment]
Ok @timforsstromAF

**Review by timforsstromAF — APPROVED** [review]

**Comment by arturchilangwa-vertel** [comment]
@FredrikArvas 
Should this merge to the DAFA project or the CRM project?

**Comment by arturchilangwa-vertel** [comment]
Module works on my machine 👍

**Pull request merged**
